print("**" * 15)
print("TAbuada")
print("**" * 15)
n = int(input("Digite seu Número para ver sua tabuada: "))
tabuada = n * 1
print(f"{n} x {1} = {n * 1}")
print(f"{n} x {2} = {n * 1}")
print(f"{n} x {3} = {n * 1}")
print(f"{n} x {4} = {n * 1}")
print(f"{n} x {5} = {n * 1}")
print(f"{n} x {6} = {n * 1}")
print(f"{n} x {7} = {n * 1}")
print(f"{n} x {8} = {n * 1}")
print(f"{n} x {9} = {n * 1}")
print(f"{n} x {10} = {n * 1}")
print("**" * 15)
