from math import sin, cos, tan, radians
print("-=" * 15)
print("Calculo de Angulo")
print("-=" * 15)
num = float(input("Digite o Angulo que voce deseja: "))
seno = sin(radians(num))
coseno = cos(radians(num))
tangente = tan(radians(num))
print(f"O Seno do {num} e de {seno:.2f}")
print(f"O Coseno do {num} e de {coseno:.2f}")
print(f"O Tangente do {num} e de {tangente:.2f}")
