from math import sin, cos, tan
print("-=" * 15)
print("Calculo de Angulo")
print("-=" * 15)
num = int(input("Digite o Angulo que voce deseja: "))
seno = sin(num)
coseno = cos(num)
tangente  = tan(num)
print(f"O Seno do {num} e de {seno}")
print(f"O Coseno do {num} e de {coseno}")
print(f"O Tangente do {num} e de {tangente}")
