print("-=" * 15)
print("Analisando Frase")
print("-=" * 15)
frase = str(input("Digite Uma Frase: ")).strip().upper()
print("A letra A Aprece ", frase.count('A'), "na Frase")
print("A Primeiroa letra A Apareceu na posição", frase.find('A') + 1)
print("A Última Letra A Apareceu na posição", frase.rfind("A") + 1)
